### ISSUE TITLE
Test roms don't compile?

### ISSUE THREAD

**Issue by orbea** [PeterLemon/SNES#12]
bass: https://github.com/ARM9/bass/commit/5af745b21a8cc68d0247eeb0b5913ffbaeb50eff
SNES: https://github.com/PeterLemon/SNES/commit/5c5c730e754114af14faff2655cb2bb098d6419b

I am trying to build the cpu test roms, but none of them seem to work.

__ADC__
```
$ bass CPUADC.asm 
error: invalid constant identifier: WRAM($0000)
LIB/SNES.INC:5:1: constant WRAM($0000)
bass: assembly failed
```
__INC__
```
$ bass CPUINC.asm 
error: invalid constant identifier: WRAM($0000)
LIB/SNES.INC:5:1: constant WRAM($0000)
bass: assembly failed
```
__MSC__
```
$ bass CPUMSC.asm 
error: invalid constant identifier: WRAM($0000)
LIB/SNES.INC:5:1: constant WRAM($0000)
bass: assembly faile
```
I compiled bass, added the binary to my $PATH and copied the `architectures` directory to `~/.local/share/bass/` so that it would be found. Am I missing something?

**Comment by thar0x29a** [comment]
Had you used bass14 (as you need) or the new bass15-18 (that wont work on this test roms atm)

**Comment by orbea** [comment]
I used the top commit of the bass repo, when I used the `v14` tag instead then compling the roms works, thanks!

Do you know why the older bass is needed here?

**Comment by thar0x29a** [comment]
Because near (the old bass autor) changed the syntax. Right now its planed that bass v19 will support both, the old and the new syntax.

**Comment by orbea** [comment]
Thanks for the details. I presume there is a code depending on both the old and new syntax already?

**Comment by thar0x29a** [comment]
https://github.com/ARM9/bass/issues/30 - The devel Branch https://github.com/ARM9/bass/tree/devel has added the old constant feature. It would be easy to add more. But atm nobody seems to have the "time" to do so.

**Comment by PeterLemon** [comment]
Thanks @thar0x29a for explaining the issue. Main syntax change was how constants in my LIB/include files need to use the new bass v18 "constant = $XXXX" style, but as the old style works with newer "devel" branch, should all be good in newer bass versions. I'm gonna close this now, have fun with your coding @orbea =D

**Comment by orbea** [comment]
Thanks for the further explanations, indeed with the changes in the devel branch at least some of the test roms build correctly. (I haven't tested them all)
