### ISSUE TITLE
PlayBRRSample.spc is not a valid spc file?

### ISSUE THREAD

**Issue by dalton-tulou** [PeterLemon/SNES#2]
Hi,

thanks for sharing your SNES code. I think your examples are very clear and easy to follow. I'm just beginning to look at SPC-700 programming. It's possible that I have found a problem with the binary file [`PlayBRRSample.spc`](https://github.com/PeterLemon/SNES/blob/master/SPC700/PlayBRRSample/PlayBRRSample.spc) in your repo. The file size is only 4976 bytes, whereas a normal spc file is more than 64K.

Cheers

**Comment by PeterLemon** [comment]
Hi dalton-tulou,

Thanks for taking an interest in my SPC-700 programming examples =D

The programming examples I have contain .spc files, but these are not normal .spc files that you can drag into SPC players...
These .spc files are actual SPC-700 binary code files, I chose .spc as the extension of this data, so it might confuse some people.
Don't worry you are not the 1st person to get confused by this ;)

If you want to hear some of my examples as actual .spc files that are playable in an SPC player checkout the files  in the root directory here:
https://github.com/PeterLemon/SNES/tree/master/SPC700

I made these .SPC files by ripping them in an emulator, & are only the main 3 tunes I have created for testing atm:
Twinkle.spc = The song from the "PlaySong" demo (Simple Twinkle Twinkle Little Star song using the harp .brr sample from FF6)
ItaloTest.spc = The song from the "ItaloTest" demo (Simple Italo Disco music test using various SNES game .brr samples)
Axel-F.spc = The song from the "Axel-F" demo (My latest creation, using old Fairlight synth samples from the 80's)

I have not made real (64kb) .spc files of all my tests like PlayBRRSample, if you request this, I shall make them for all my demos =D

P.S in the PlayTwoSong demo test you need to press either the A or B button on the SNES controller to play 1 of 2 songs.

I hope this info helps you out, I am going to close this issue now, have fun, & good luck with your SPC-700 programming =D

**Comment by dalton-tulou** [comment]
Thanks for explaining that, it makes sense! ItaloTest and Axel-F sounds cool :)
