### ISSUE TITLE
Tetris Battle Gaiden Translation Started not working

### ISSUE THREAD

**Issue by Darknior** [PeterLemon/SNES#5]
Hi

Sorry to boring you, but i try to use your IP and it don't work for me, all the game is always in japanese.
I read you translate some text of the start of the story and i can't see them.
My options are all in english, i also try with the BOSS HACK but same result.

Can you help me ?
Please, will you continue this old translation ?
Because this game is the BEST EVER Tetris of the world and nobody never translate it :(
Thanks a lot

**Comment by PeterLemon** [comment]
hi Darknior,

No I do not think it is boring for you to message me, I love it when people are interested in my translation work =D

I have only translated a tiny amount of Tetris Battle Gaiden, right now I have only done the options screen, & the text of the rolling demo, which you will see if you wait long enough on the title screen.
I will try todo more work for this translation soon =D

This is one of my favourite Tetris games too, so I will try to get it done!

**Comment by Darknior** [comment]
Thanks a lot, now i see what you translate :)
I'm really so happy to know you will continue it and my friends too, we love playing this fantastic game ...

When you will release it i wish it will work fine too with the Bosses Hack.
https://www.romhacking.net/hacks/3203/

**Comment by Darknior** [comment]
WOAW so excellent i've read your last comit to this project :)
You translate all the game, maybe you forgot the "Super attack" list, i don't see them ?
Can you update the IPS patch please, i d'ont understand how to generate it.

I really wish to try your new patch :)
When it will be done, do you want i post your patch on Romhack ?
Thanks

**Comment by PeterLemon** [comment]
Hi Darknior,

I have not forgotten the pause screen "Super attack" list, I am doing that next ;)

The .ips patch has been updated to the latest source code hack.
You can try it now =D

I am a member of Romhack, so I would like to release the finished translation patch myself, thanks anyway ;)

**Comment by Darknior** [comment]
Ok thanks i will try it now :)
Because with the last one i found one screen you forgot to translate : 

![tetris battle gaiden japan hack 1 0 by docrow -180402-202226](https://user-images.githubusercontent.com/3703317/38210069-8ec93dfc-36b6-11e8-9967-560c239884c6.png)
