### ISSUE TITLE
Syntax highlighter

### ISSUE THREAD

**Issue by Phillip-May** [PeterLemon/SNES#6]
These examples are very clear and useful to have when trying to make custom homebrew. I would done this as a private message but you don't have an email publicly listed so I made an issue.
Given the amount you have programmed, do you have a custom profile with all the snes bass opcodes for a text editor?

**Comment by PeterLemon** [comment]
Hi Phillip,

No I have not made a custom syntax highlighter for the snes opcodes in bass.
If you would like to make your own, you can checkout the bass SNES table here for help: https://github.com/ARM9/bass/blob/master/bass/arch/table/snes-cpu.arch

**Comment by mrehkopf** [comment]
FWIW I made a 65816 assembly highlighting description that can be used with TextMate, Sublime Text, Visual Studio Code and probably others (*.tmLanguage file). I wasn't satisfied with the highlighting available as a package which seemed fairly limited to me. Not sure whether it's release quality yet.
It is currently tailored to SNESCOM syntax (SNES assembler made by @bisqwit) and looks like this:
![grafik](https://user-images.githubusercontent.com/238664/37655408-798cc650-2c45-11e8-9a00-30e2b426e027.png)

**Comment by PeterLemon** [comment]
Thanks mrehkopf =D
