### ISSUE TITLE
GSUWait macro branches on incorrect condition

### ISSUE THREAD

**Issue by RedGuyyyy** [PeterLemon/SNES#7]
Hi.  The following macro is branching (looping) when the GO bit is clear in the GSU SFR, but it should really branch when the GO bit is set.  I believe the 'beq' should be replaced with a 'bne'.  I saw this in the ADC test, but it is likely in other tests.

macro GSUWait() { // Wait For GSU To Finish
{#}GSUBusy:
    lda.w GSU_SFR // X = GSU Status/Flag Register
    bit.b #GSU_SFR_GSU // Check GSU Is Running
    beq {#}GSUBusy **_<- should be bne_**
}

**Comment by PeterLemon** [comment]
Hi RedGuyyyy,

Many thanks you were correct, I have fixed up all my demos to use this fix.
As a bonus they all now run in SNES9x & ZSNES now too =D
