### ISSUE TITLE
Tetris Battle Gaiden Image Translation help

### ISSUE THREAD

**Issue by Darknior** [PeterLemon/SNES#8]
Hi

I have try your last translation IPS patch from 3 days ago and its really cool to have now : 

- CHARACTERDESCRIPTION
- INTRO
- PAUSE
- SETTING

Updates : 

- On intro your forgot to translate the character name : 

![info](https://user-images.githubusercontent.com/3703317/38134001-af0883ae-3411-11e8-8656-c6e33bf51bc8.jpg)

Maybe it is an image, they write it same on character select screen. If it is and you can give me the format and size and number color i must use, or the original image, i can made them for you on photoshop.

- Select screen is the most important game screen i think because it's wher we select our magics spells.

![select character](https://user-images.githubusercontent.com/3703317/38134113-fe8570fe-3411-11e8-870b-011ff060f2e1.jpg)

Maybe the character name is an image ? But all other is real text.

- Title screen, the book is an image with MOD7 effect, with the original one i can make it in english for you, only give me the text, i'm not sure they write TETRIS BATTLEGAIDEN
The Balls can be translate too, i can do it too.

![menu](https://user-images.githubusercontent.com/3703317/38134191-42fd69e4-3412-11e8-978e-f17bbccab8d9.jpg)

I don't know if the text menu (Story Mode, Battle Mode, Options) is text or images.

- The GAME OVER screen, important for children to read YES or NOT to continue ;)
The WIN and LOOSE word are maybe images with an color effect animation ... if it is i can help if you give me the originals, or the color and size i must use ?

![lost game](https://user-images.githubusercontent.com/3703317/38134355-e8d40de6-3412-11e8-96bc-daad91a7ec22.jpg)

- And at last the Story mode, cool to understand it one day if possible, but less important. And i can't help you it's only text words. And the MAP is already translated.

![story](https://user-images.githubusercontent.com/3703317/38134289-9e480f16-3412-11e8-99fc-ca8e5a98443d.jpg)

Thanks for all your work

**Comment by Darknior** [comment]
It's not a final version, i don't know what font to use to do it like in the other game text ... but it's to show you an exemple.

![book us](https://user-images.githubusercontent.com/3703317/38135763-4dc6e30c-341a-11e8-9cd9-26e78ab4f2de.png)

**Comment by PeterLemon** [comment]
Hi Darknior,

I am a pixel artist, so I will try todo all the GFX replacements (art & hacking) all by myself...
But if I get stuck, do not have enough time, or my art looks bad, I will def ask for your help on this =D

I do not know the final image size for all these gfx, because I might hack them to be bigger, so I will know what todo when I get to it.

Thanks for taking an interest in my work =D

P.S Your "Battle Gaiden" GFX test looks great!

**Comment by Darknior** [comment]
Thanks, no problem :)
Yes it is but i think we can do better with an other font, or use a font a little higher to see better the "A" letter.

**Comment by Darknior** [comment]
WOAW excellent, i come today here to ask you some news about this great project and discover i miss your last commit two month a go :(
I have dl the IPS and try it ...
You have translated all the **Characters name** and **Magic name** ... so cool :)
Thanks a lot.

Do you will improve it again for : 
- Game Over screen
- Title Screen
- Story Mode

Thanks a lot again

**Comment by PeterLemon** [comment]
Yep I'll try to get these all done =D

**Comment by Darknior** [comment]
I m your beta tester 😉
Think to me.

**Comment by Darknior** [comment]
I really love your work, thanks a lot to continue to work on this project, the game is near finished :D

**Comment by PeterLemon** [comment]
Darknoir, thanks so much =D
I am in the final stages of the translation, def helps me want todo it with your motivation!

**Comment by Darknior** [comment]
Your work is really good and applied. I played a lot with your last patch and I have not detected any bug so far.
Finally all that is missing is the 'Game Over' screen, the texts of the 'Story Mode' and the "Continues" screen with the choice 'Yes / No'.
As I already told you if you need help I'm here ;)

**Comment by Taranchul** [comment]
I also want to thank you very much, Peter. Finally, a friend of mine and I can play this game without "flying blind" regarding the options and character specials. :D That said, playing the story mode knowing what's going on would be even more fantastic. But that's only a bonus for us, the 2P mode is much more important. Great work!

**Comment by PeterLemon** [comment]
Thanks Taranchul, I grew up playing this game in early 90's with my friends, so really want to get 100% translation completed! I def love that people are interested like you & Darknior, really motivates me =D

**Comment by Taranchul** [comment]
Go, Peter, go! :D And also thanks from my friend. She was very exited when I told her that we can play this game in English on our next gaming night. \o/

**Comment by Kwoken** [comment]
Hi, just wanted to add to the voices of support here.  Stumbled across your work when I wondering if anyone had translated Albert Odyssey, so I'm doubly pleased to see you're also working on Tetris Battle Gaiden.  What's the status of the projects? Is AO complete?

**Comment by PeterLemon** [comment]
Hi Kwoken,
Well Albert Odyssey was the 1st game I tried to translate on the snes, so another person got further than me & I thought they would complete it, but I think they gave up, so if I work on it again I would do lots differently using my new knowledge. I may work on AO again once Tetris Battle Gaiden is complete. Thanks for the encouraging words =D

**Comment by Kwoken** [comment]
These are among my favourite games from the SNES days and I used to play the hell out of them =)  I think I still have my hand scrawled translation notes knocking about somewhere for TBG.
I worked on a couple of SNES titles back in the day, though it's been a while since I seriously pushed pixels.  I'm not sure how best to get in touch directly via GitHub, but if there's anything on the art or maybe writing side that I could help with, especially with regard to AO, then do let me know.

**Comment by Darknior** [comment]
For my part i always stand for a new BG update :p 
You have almost finished it .... so impatient :D 
Thanks a lot

**Comment by PeterLemon** [comment]
heh thanks so much, I'll try todo more work on it soon ;)

**Comment by DadPool09** [comment]
I signed up to Github just to say thank you for taking on this project during your free time. Last night I tested out your patch successfully and absolutely enjoy the progress made so far.

**Comment by clach04** [comment]
@PeterLemon just a quick thank you, I just tried out this patch and it's instantly more accessible now :)

**Comment by PeterLemon** [comment]
clach04 thanks so much, it really does motivate me to finish this translation, glad you are already finding it useful ;)

**Comment by Darknior** [comment]
Really excited to read you plan to finish it :D Thanks a lot ...

**Comment by PeterLemon** [comment]
Hi everyone, a full 100% translation of Tetris Battle Gaiden got released, so I'm discontinuing my translation.
You can find it here: https://www.romhacking.net/translations/5737/
Thanks for all your support, I think you will like what DDS translation have done with it ;)
I'm now closing this issue.

**Comment by Taranchul** [comment]
Although it's great to finally have a complete translation, it's a little sad that yours wasn't meant to become it. For me, it will always have a place of honour for being the one letting us play this game more than a year before the other one got released. Many thanks for your effort!

**Comment by Darknior** [comment]
Yes thanks i already see it but i'm sad  it's not your version and your work ....
So bad you left so many time to finish your work :( 
And i don't understand why they have renamed the game in "Tetris Spin Off" ??? :(

**Comment by Taranchul** [comment]
> And i don't understand why they have renamed the game in "Tetris Spin Off" ??? :(

Because that's what "Gaiden" means in japanese.

https://jisho.org/word/%E5%A4%96%E4%BC%9D

That said, I would've left the title untranslated for its recognition value.

**Comment by Darknior** [comment]
> That said, I would've left the title untranslated for its recognition value.
Ok i understand it's what i mean but your idea was better :p
