### ISSUE TITLE
SNES Translations ?

### ISSUE THREAD

**Issue by Darknior** [PeterLemon/SNES#9]
Hi

It is not really an issue, but there are no informations about your games translation ...
You release two of them with other members from Romhack :
 
- Super Naxat Open: Golf de Shoubu da! Dorabocchan (EN)
https://www.romhacking.net/translations/4096/
https://www.youtube.com/watch?v=iXIzYQ4NLxQ
- Super Soukoban (EN)
https://www.romhacking.net/translations/3313/
https://www.youtube.com/watch?v=hOEMdJSbXCs

But for the others ? Can we try them and know almost what is missing please ?
Thanks a lot.

- Albert Odyssey
https://github.com/PeterLemon/SNES/tree/master/Translate/Albert%20Odyssey
https://www.youtube.com/watch?v=jrYbdIXNLqQ
- Soreyuke Ebisumaru Karakuri Meiro - Kieta Goemon no Nazo!!
https://github.com/PeterLemon/SNES/tree/master/Translate/Soreyuke%20Ebisumaru%20Karakuri%20Meiro%20-%20Kieta%20Goemon%20no%20Nazo!!
https://www.youtube.com/watch?v=F8t4ALnJaeo

**Comment by PeterLemon** [comment]
ah yep I should put up links to my github for the completed Super Naxat Golf & Super Soukoban translations. Albert Odyssey & the Goemon Puzzle game are not complete yet!

**Comment by PeterLemon** [comment]
O.k I have added Readme.md files pointing to the complete translations on romhacking for Super Naxat Golf & Super Soukoban =D
